stages:
  - deploy
  - test
  - switch
  - cleanup

deploy_green:
  stage: deploy
  script:
    - kubectl apply -f green-deployment.yaml

test_green:
  stage: test
  script:
    - curl -f http://green-app-url/health

switch_traffic:
  stage: switch
  script:
    - kubectl patch service my-app -p '{"spec":{"selector":{"version":"green"}}}'

cleanup_blue:
  stage: cleanup
  script:
    - kubectl delete deployment my-app-blue

