apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
    version: blue  # Initially routing to Blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

